() configure fixes    --enable-debug to build .mdb files 	--with-log4net=[log4net] to override default pkg-config file

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -7,23 +7,20 @@ AC_PROG_INSTALL
 pmsdir=$libdir/mono/2.0
 AC_SUBST(pmsdir)
 
-dnl pkg-config
-AC_PATH_PROG(PKG_CONFIG, pkg-config, no)
-if test "x$PKG_CONFIG" = "xno"; then
-	AC_MSG_ERROR([You need to install pkg-config])
-fi
-
-dnl C# compiler
 AC_PATH_PROG(AL, al, no)
 AC_PATH_PROG(CSC, csc, no)
 AC_PATH_PROG(MCS, gmcs, no)
 AC_PATH_PROG(MONO, mono, no)
 AC_PATH_PROG(GACUTIL, gacutil, no)
+AC_PATH_PROG(PKG_CONFIG, pkg-config, no)
 
-CS="C#"
+if test "x$PKG_CONFIG" = "xno"; then
+	AC_MSG_ERROR([You need to install pkg-config])
+fi
+
 if test "x$CSC" = "xno" -a "x$MCS" = "xno"  ; then
 	dnl AC_MSG_ERROR([You need to install a C# compiler])
-	AC_MSG_ERROR([No $CS compiler found])
+	AC_MSG_ERROR([No csharp compiler found])
 fi
 
 if test "x$MCS" = "xno" ; then
@@ -34,13 +31,38 @@ if test "x$MONO" = "xno"; then
 	AC_MSG_ERROR([No mono runtime found])
 fi
 
-GACUTIL_FLAGS='-root $(DESTDIR)/usr/lib'
+AC_ARG_WITH([log4net],
+	[  --with-log4net=<pkg name>   Override default log4net package], 
+	[], 
+	[with_log4net=log4net]
+)
+AC_SUBST([PKGLOG4NET], [$with_log4net])
+
+AC_ARG_ENABLE([debug],
+	[  --enable-debug   Create debug files (.mdb)], 
+	if test "x$enable_debug" = "xyes"; then
+		DEBUG_FLAGS='-debug'
+	fi
+)
+
 
 AC_SUBST(AL)
 AC_SUBST(MCS)
 AC_SUBST(MONO)
 AC_SUBST(GACUTIL)
-AC_SUBST(GACUTIL_FLAGS)
+AC_SUBST(PKG_CONFIG)
+AC_SUBST(DEBUG_FLAGS)
+AC_SUBST([GACUTIL_FLAGS], ['-root $(DESTDIR)/usr/lib'])
+
+
+AC_MSG_CHECKING(for log4net >= 1.2)
+if $PKG_CONFIG $PKGLOG4NET; then
+	AC_MSG_RESULT($PKGLOG4NET)
+else
+	echo "log4net dev package is missing";
+	exit 1;
+fi
+
 
 AC_OUTPUT([
 			  Makefile
